# Calcul Numeric - Laborator 2 - NumPy

## Module/Pachete/Biblioteci
Definiții:

- Module: Un modul este un fișier care conține funcții Python, variabile globale etc. Este pur și simplu un fișier .py care conține cod/executabil Python.

- Pachete: Un pachet este un spațiu de nume care conține mai multe pachete/module. Este un director care conține un fișier special init.py.

- Biblioteci: O bibliotecă este o colecție de diferite pachete. Conceptual, nu există diferență între pachet și bibliotecă în Python.

Modulele/pachetele/bibliotecile pot fi ușor "importate" și făcute funcționale în codul tău Python. Un set de biblioteci este inclus în fiecare instalare Python. Altele pot fi instalate local și apoi importate. Propriul tău cod aflat în altă parte pe computerul tău (local) poate fi de asemenea importat.

In [ ]:
###### toate "chestiile" din biblioteca math pot fi utilizate
import math
print(math.pi)

# poți atribui o etichetă bibliotecii math pentru comoditate
import math as m
print(m.pi)

# alternativ, poți importa doar un anumit "element" din bibliotecă
from math import pi    # poți adăuga mai multe elemente deodată, le listezi separate prin ","
# from math import pi, sqrt
print(pi)

# sau poți importa totul (foarte periculos!!!)
from math import *
print(sqrt(7))

## NumPy

NumPy este un pachet fundamental pentru calculul științific în Python. Conține, printre altele:

- obiecte array de tip tablou N-dimensional
- operații sofisticate și rapide cu array-uri
- instrumente pentru integrarea codului C/C++ și Fortran (nu le vom discuta în acest laborator din păcate)
- generare de numere (pseudo-)aleatoare
- algebră liniară, transformate Fourier și multe altele


Link către documentația NumPy: https://numpy.org/doc/stable/user/whatisnumpy.html

Există convenția ca denumirea acestui pachet să se prescurteze cu alias-ul `np`. NumPy se importă cu următoarea comandă: 

In [25]:
import numpy as np 

Dacă nu aveți instalat pachetul, folosiți `pip`:

In [3]:
!pip install numpy

### Array-urile NumPy

Array-urile NumPy diferă de listele Python, deoarece NumPy oferă:

- suport complet pentru tablouri multidimensionale
- eficiență
- proiectat pentru calcul științific (comoditate)

Similar altor limbaje de programare care au un focus specific (de exemplu, "orientat pe obiect"), array-urile în numpy sunt atât de centrale încât dezvoltarea aplicațiilor științifice poate fi considerată "orientată pe array-uri".

Array-urile (tablourile) NumPy au o dimensiune fixă la creare, spre deosebire de listele Python (care pot crește dinamic). Modificarea dimensiunii unui ndarray va crea un nou tablou și va șterge originalul.

Elementele dintr-un tablou NumPy trebuie să fie de același tip de date și, astfel, vor avea aceeași dimensiune în memorie. Excepția: se pot avea tablouri de obiecte (Python, inclusiv NumPy), permițând astfel tablouri de elemente de dimensiuni diferite.

Tablourile NumPy facilitează operațiile matematice avansate și alte tipuri de operații pe un număr mare de date. În mod tipic, astfel de operații sunt executate mai eficient și cu mai puțin cod decât este posibil utilizând secvențele încorporate în Python.

O demonstrație a eficienței NumPy:

In [4]:
# standard python
L = range(1000)
print('cu python normal: ')
%timeit [i**2 for i in L]

# numpy
a = np.arange(1000)
print('cu numpy: ')
%timeit a**2

cu python normal: 
46.9 µs ± 1.79 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
cu numpy: 
823 ns ± 105 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


#### De câte ori este mai rapid NumPy decât Python-ul standard?

### Tipuri de date în NumPy

Un array NumPy este o grilă de valori omogene (toate de același tip) și este indexat printr-un tuplu de numere întregi pozitive.

Toate tipurile de date standard sunt disponibile:

In [8]:
# Tipul trebuie specificat atunci când se creează tabloul
a = np.array([1, 2, 3], 'float64')
print(a, a.dtype, '\n')
a = np.array([1, 2, 3], 'uint32')
print(a, a.dtype, '\n')

# Alternativ, putem lăsa Python să deducă tipul:
a = np.array([1, 2, 3.3])
print(a, a.dtype, '\n')

# Sunt permise și numerele complexe
a = np.array([1+2j, 3+4j, 5+6*1j])
print(a, a.dtype, '\n')

# Booleene
a = np.array([True, False, False, True])
print(a, a.dtype, '\n')

# Tipuri non-numerice sunt, de asemenea, permise: șiruri de caractere
a = np.array(['Python', 'bună ziua', 'suspendarea activității'])
print(a, a.dtype, '\n')

[1. 2. 3.] float64 

[1 2 3] uint32 

[1.  2.  3.3] float64 

[1.+2.j 3.+4.j 5.+6.j] complex128 

[ True False False  True] bool 

['Python' 'bună ziua' 'suspendarea activității'] <U23 



### Dimensiuni
Numărul de dimesiuni este rank-ul array-ului. Forma (shape-ul) unui array este o pereche (tuplu) de întregi care indică dimensiunea tabloului de-a lungul fiecărei dimensiuni.
#### Tablouri 1D

In [26]:
a1 = np.array([0, 1, 2, 3])
print("array: \n", a1)
print("rank:", a1.ndim)
print("shape:", a1.shape)
print("marimea primei dim (axis):", len(a1)) # not recommended in >1D

array: 
 [0 1 2 3]
rank: 1
shape: (4,)
marimea primei dim (axis): 4


#### Tablouri 2D

In [27]:
a2_3 = np.array([[0, 1, 2], [3, 4, 5]])
print("2 x 3 array: \n", a2_3)
print("rank:", a2_3.ndim)
print("shape:", a2_3.shape)
print("marimea primei dim (axis):", len(a2_3))

2 x 3 array: 
 [[0 1 2]
 [3 4 5]]
rank: 2
shape: (2, 3)
marimea primei dim (axis): 2


#### Tablouri 3D

In [28]:
a2_3_4 = np.array([[[1, 10, 100, 1000], [2, 20, 200, 2000], [3, 30, 300, 3000]], 
                   [[4, 40, 400, 4000], [5, 50, 500, 5000], [6, 60, 600, 6000]]])
print("2 x 3 x 4 array:\n", a2_3_4)
print("rank:", a2_3_4.ndim)
print("shape:", a2_3_4.shape)
print("marimea primei dim (axis):", len(a2_3_4))

2 x 3 x 4 array:
 [[[   1   10  100 1000]
  [   2   20  200 2000]
  [   3   30  300 3000]]

 [[   4   40  400 4000]
  [   5   50  500 5000]
  [   6   60  600 6000]]]
rank: 3
shape: (2, 3, 4)
marimea primei dim (axis): 2


In [ ]:
np.array([a,b,c,d])

### Inițializarea tablourilor
Tablourile pot fi create din liste, dar și liste pot fi obținute din tablouri (cu toate acestea, amintiți-vă că cele două nu sunt echivalente, deoarece un tablou NumPy nu este o listă):

In [29]:
l = [0, 1, 2, 3]
a = np.array(l)
print(a.tolist(), type(a.tolist()))

[0, 1, 2, 3] <class 'list'>


Folosind `arange` și `linspace`:

In [38]:
# distanțat uniform:
print(np.arange(1, 9, 2)) # la fel ca "range": start, end (exclusiv), pas

# la fel, dar precizând numărul de elemente:
print(np.linspace(0, 1, 2)) # start, end, nr elemente 

[1 3 5 7]
[0. 1.]




### Exercițiu
- creați un tablou NumPy cu toate numerele pare de la 1 la 100 (inclusiv 100)

<img width=200 src='https://i.imgflip.com/8gogcy.jpg'/>

In [ ]:
# Exercițiu







Inițializarea unor tablouri triviale:

In [11]:
# matrice 3x3 de 1
ones = np.ones((3, 3))
print(ones, '\n')

# matrice 2x2 de zerouri
zeros = np.zeros((2, 2))
print(zeros, '\n')

# matricea unitate 3x3
unity3d = np.eye(3)
#unity3d = np.identity(3) # np.identity este echivalent cu np.eye
print(unity3d, '\n')

# matrice diagonală
diagonal = np.diag(np.array([1, 20, 3, 4]))
print(diagonal, '\n')

# matrice creată din compresiune de listă
array = np.array([(i, j) for i in range(2) for j in range(3)])
print(array, '\n')


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

[[0. 0.]
 [0. 0.]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

[[ 1  0  0  0]
 [ 0 20  0  0]
 [ 0  0  3  0]
 [ 0  0  0  4]] 

[[0 0]
 [0 1]
 [0 2]
 [1 0]
 [1 1]
 [1 2]] 



### Redimensionarea și concatenarea
Un tablou 1D poate fi redimensionat într-un array cu mai multe dimensiuni

In [31]:
a = np.arange(0, 6)
m = a.reshape(3, 2) 
# Aveți grijă, redimensionarea trebuie să fie validă. Numărul total de elemente rămâne la fel: 1 x 6 = 3 x 2. 
# e.g. nu puteți redimensiona un tablou cu 100 de elemente într-unul cu dimensiunile 3x50, deoarece sunt necesare 3x50=150 elemente

print("original:", a, '\n')
print("reshaped:", m, '\n')

a_from_m = m.flatten()
print("flattened array (înapoi la original):", a_from_m, '\n')

# când aplicam flatten(), array-urile multidimensionale se reduc la o singură dimensiune - obținem un tablou 1D cu toate elementele

original: [0 1 2 3 4 5] 

reshaped: [[0 1]
 [2 3]
 [4 5]] 

flattened array (înapoi la original): [0 1 2 3 4 5] 



### Exercițiu

- redimensionați următorul tablou într-un tablou tridimensional:

In [ ]:
# Exercițiu

a = np.zeros((5, 90))







Operația de concatenare:

1D

In [32]:
# concatenare 1D
a = np.array([1, 2])
b = np.array([3, 4, 5, 6])
c = np.array([7, 8, 9])

print(f"a={a}")
print(f"b={b}")
print(f"c={c}")
print("concatenare unidimensională (a+b+c):", np.concatenate((a, c, b)))

a=[1 2]
b=[3 4 5 6]
c=[7 8 9]
concatenare unidimensională (a+b+c): [1 2 7 8 9 3 4 5 6]


2D

In [4]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(f"a={a}")
print(f"b={b}")

print("concatenare default 2D (a+b):",'\n', np.concatenate((a, b)))
print("concatenare după prima axă (a+b):",'\n', np.concatenate((a, b), axis=0))
print("concatenare după a doua axă (a+b):",'\n', np.concatenate((a, b), axis=1))

a=[[1 2]
 [3 4]]
b=[[5 6]
 [7 8]]
concatenare default 2D (a+b): 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
concatenare după prima axă (a+b): 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
concatenare după a doua axă (a+b): 
 [[1 2 5 6]
 [3 4 7 8]]


### Copii și vederi
Fiind obiecte mutabile, tablourile NumPy pot avea **copii (copies)** și **vederi (views)**:

In [33]:
a = np.array([1, 2, 3])
b = a # aceasta este o vedere - un view
c = a.copy() # aceasta este o copie

# Modificările aplicate tabloului a modifică și tabloul b
# (care, de fapt, sunt același PyObject)
a[0] = 7
print(a, b, c)

# ... și invers
b[1] = 7
print(a, b, c)

# Modificările asupra lui c nu modifică tabloul a
c[0] = 9
print(a, b, c)

# Obiectul Python este același pentru a și b, dar diferit pentru c:
print("Sunt a și b același obiect?", np.may_share_memory(a, b))
print("Sunt a și c același obiect?", np.may_share_memory(a, c))

[7 2 3] [7 2 3] [1 2 3]
[7 7 3] [7 7 3] [1 2 3]
[7 7 3] [7 7 3] [9 2 3]
Sunt a și b același obiect? True
Sunt a și c același obiect? False


**Atenție!** metoda copy se folosește doar asupra tablourilor NumPy, nu și pentru temele de laborator ale colegilor

### Exercițiu
- verificați dacă np.array.reshape returnează o vedere sau o copie

In [ ]:
# Exercițiu




Rețineți că, pentru obiectele numpy, funcția id() nu funcționează întotdeauna (no idea why). Pentru a verifica dacă două variabile indică același PyObject, utilizați np.may_share_memory().

### Indexare
Elementele unui tablou pot fi accesate și atribuite în aceeași manieră ca și alte secvențe Python (de exemplu, liste):

In [ ]:
a = np.arange(10)
print(a[0], a[2], a[-1])

# reminder: [start:stop:step] funcționează la fel de bine.
print(a[2:9:3])
print(a[::-1]) # step poate fi negativ și se obține astfel o secvență inversată.

![](https://i.ibb.co/23qjk2P/numpy-indexing.png)

### Exercițiu

- crează NumPy array-ul folosit în exemplul de mai sus și afișează cele patru subarray-uri


In [ ]:
# Exercițiu








Pentru tablourile multidimensionale, indecșii sunt tupluri de întregi.

Notă:

- în 2D, prima dimensiune corespunde rândurilor, iar a doua coloanelor.
- pentru un tablou multidimensional a, a[0] este interpretat prin luarea tuturor elementelor în dimensiunile nespecificate.

### Feliere (Slicing)
Operația de feliere (slicing) creează o vedere asupra tabloului original, care este doar o modalitate de a accesa datele tabloului. Atunci când se modifică o vedere, tabloul original este de asemenea modificat.

In [ ]:
a = np.diag(np.arange(3))
print(a, '\n')
print(a[1, 1], '\n')
print(a[2], '\n')

# feliază tabloul original, creând o vedere
b = a[1:, 1:]
print(b, '\n')

# modificarea vederii modifică și tabloul original
b[-1, -1] = 10
print(a, '\n')

# verifică dacă b este efectiv o vedere a lui a
print("Sunt a și b același obiect?", np.may_share_memory(a, b))

In [ ]:
a = np.arange(35).reshape(7, 5)
print('a = ', a)
print('Extragem primele 4 elemente de pe rândul cu index 2 (al treila rând):', a[2, :4])
print('Extragem elementele cu index 2,3 de pe ultimile două rânduri:', a[-2:, 2:4])

### Exercițiu
- Extrage rândul central. Verifică shape-ul tabloului extras.
- Extrage coloana centrală. Verifică shape-ul tabloului extras.
- Extrage ultimele 3 elemente de pe primele 4 rânduri.

In [ ]:
# Exercițiu
a = np.arange(35).reshape(7, 5)






### Indexare avansată (Fancy indexing)
Tablourile NumPy pot fi indexate cu feliere (slices), dar și cu șiruri booleane sau șiruri de întregi (măști). Această metodă se numește indexare avansată (fancy indexing) și creează copii, nu vederi.

In [34]:
a = np.arange(0, 21, 2)
print("array original:", a,'\n')

mask = (a % 3 == 0)
print("mask:", mask,'\n')

filtered_a = a[mask]
# echivalent cu a[a%3==0]
print("tabloul fitrat:", filtered_a,'\n')

# verifică dacă indexarea avansată creează copie 
print("Sunt a și filtered_a același obiect?", np.may_share_memory(a, filtered_a), '\n')

# indexarea cu o mască poate fi folosită pentru asignarea a noi valori pentru sub-tablouri.
a[a % 3 == 0] = -1
print("array modificat:", a, '\n')

array original: [ 0  2  4  6  8 10 12 14 16 18 20] 

mask: [ True False False  True False False  True False False  True False] 

tabloul fitrat: [ 0  6 12 18] 

Sunt a și filtered_a același obiect? False 

array modificat: [-1  2  4 -1  8 10 -1 14 16 -1 20] 



Indexarea poate fi realizată cu un șir de numere întregi, unde același index poate fi repetat de mai multe ori.

In [ ]:
a = np.arange(0, 100, 10)
l = [2, 3, 2, 4, 2] # listă python cu indecși
print("selecția cu indecșii de mai sus: ", a[l], '\n')

Atunci când se creează un tablou nou prin indexarea cu un șir de numere întregi, noul tablou are aceeași formă ca și șirul de întregi:

In [ ]:
a = np.arange(0, 20, 2)
idx = np.array([[3, 4],[9, 7]])
a[idx]

![](https://i.ibb.co/7p3X8R0/numpy-fancy-indexing.png)

### Operații cu tablouri
#### Operații elementare
În mod implicit, toate operațiile (adunări, scăderi, înmulțiri, ...) cu tablouri sunt efectuate element-cu-element:

In [35]:
# operații cu scalari
a = np.arange(4)
print(a, '\n')
print(a * 5, '\n')

# ridicarea la putere
print(2 ** a, '\n')

[0 1 2 3] 

[ 0  5 10 15] 

[1 2 4 8] 



In [15]:
# operații între tablouri unidimensionale. De asemenea, și în acest caz, toate operațiile sunt efectuate element-cu-element
a = np.arange(4)
b = np.ones(4) + 1
print(a, b)
print("a - b:", a - b)
print("a * b:", a * b)

[0 1 2 3] [2. 2. 2. 2.]
a - b: [-2. -1.  0.  1.]
a * b: [0. 2. 4. 6.]


**Atenție!** 
deoarece operațiile sunt efectuate element-cu-element în toate dimensiunile, înmulțirea tablourilor nu este înmulțire matriceală:

In [7]:
ones = np.ones((3,3))
print ('matrice orginală:','\n',ones,'\n')

print ('produsul element-cu-element "*": ','\n',ones*ones,'\n')

print ('produsul matematic: ','\n',ones.dot(ones),'\n')

matrice orginală: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

produsul element-cu-element "*":  
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

produsul matematic:  
 [[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]] 



#### Comparații


In [ ]:
# element-cu-element
print('egalitate?:', np.array([1, 3, 2, 5]) == np.array([3, 1, 2, 5]))
print('mai mare ca?:', np.array([1, 3, 2, 5]) > np.array([3, 1, 2, 1]))

# comparație între array-uri
print(np.array_equal(np.array([1, 3, 2, 5]), np.array([3, 1, 2, 1])))

#### Operații logice

In [ ]:
a = np.array([1, 1, 0, 0], bool)
b = np.array([1, 0, 1, 0], bool)
print("SAU logic:", np.logical_or(a, b))
print("ȘI logic:", np.logical_and(a, b))

#### Aplicarea de funcții 

In [ ]:
# funcțiile matematice există și în NumPy, și se pot aplica unui între array (element-cu-element)
a = np.arange(1, 9)
print("sin:", np.sin(a))
print("log:", np.log(a))

# funcționează și pe tablouri multi-dimensionale
m = a.reshape(2, 4)
print("exp:", np.exp(m))

#### Transpusa unei matrice

In [ ]:
# extragere
a = np.arange(16).reshape(4,4)

print ("a:", '\n', a , '\n')

print ("transpusa:", '\n', a.T , '\n') # a.T este o vedere

Există un pachet de algebră liniară în NumPy și se numește `numpy.linalg`. Cu toate acestea, în ceea ce privește performanța, pachetul inclus în scipy, numit și `scipy.linalg`, este mai bun și mai eficient.

#### Reduceri (reduction)
Operațiile care reduc dimensionalitatea tablourilor sunt numite reduceri. Funcțiile de reducere operează asupra elementelor unui tablou și returnează un (set de) scalar(i), și sunt disponibile fie ca metode ale clasei de tablouri, fie ca funcții NumPy.

Pentru tablouri multi-dimensionale, axa trebuie specificată.

In [ ]:
a = np.arange(1,7)
print(a)
print("suma:", a.sum(), np.sum(a))
print("min:", a.min(), np.min(a))
print("max:", a.max(), np.max(a))
print("index arg min:", a.argmin(), np.argmin(a))
print("index arg max:", a.argmax(), np.argmax(a))
print("media:", a.mean(), np.mean(a))
print("mediana:", np.median(a)) 
print("deviația standard:", a.std(), np.std(a))
# și multe altele... pentru detalii întrebați ChatGPT (sau consultați documentația)

In [ ]:
# pentru mai multe dimensiuni:

m = a.reshape(3,2)
print(m, '\n')

print("suma pe coloane:", m.sum(axis=0))
print("suma pe rânduri:", m.sum(axis=1))

#### Broadcasting
Ați văzut că am folosit operațiile element-cu-element doar pe tablouri de același rang și formă. Cu toate acestea, este, de asemenea, posibil să se facă operații pe tablouri de dimensiuni diferite dacă NumPy poate transforma (extinde) aceste tablouri astfel încât toate să aibă aceeași dimensiune.

![](https://i.ibb.co/PxL2dsJ/numpy-broadcasting.png)

In [ ]:
a = np.tile(np.arange(0, 40, 10), (3, 1)).T # consultă documentația să vezi ce face np.tile
print("array inițial:", '\n', a, '\n')
print("suma obținută prin broadcasting:", '\n', a + np.arange(3), '\n')

In [ ]:
a = np.reshape(np.arange(0, 40, 10), (4, 1)) # aplicăm reshape pentru a transforma în coloană
# sau cu transpusa
# a = np.array([np.arange(0, 40, 10)]).T
# sau cu np.newaxis - vezi celula următoare

print(a, a.shape)

b = np.arange(3)
print(b, b.shape)

# broadcasting - suma între o coloană și un rând este o matrice
# rândul/coloana se multiplică astfel încât însumarea să fie posibilă - vezi figura de mai sus
a + b

#### Manipularea formei

In [ ]:
# adăugarea unei dimensiuni 
print("dimensiune nouă pentru axa 1:", '\n', np.arange(1,4)[:,np.newaxis], '\n')
print("dimensiune nouă pentru axa 0:", '\n', np.arange(1,4)[np.newaxis,:], '\n')

# resizing
print ("resizing:", '\n', np.resize(np.arange(4), (9,)), '\n')  
# elementele încep să se repete dacă dimensiunea finală este mai mare

### Generare de numere random
Există două module pentru numere (pseudo)aleatoare. Modulul `numpy.random` este cel mai simplu de utilizat.

In [36]:
import numpy.random as npr
npr.seed(223) # seed pentru reproducerea rezultatelor, modifica-l în numărul tău favorit și vezi ce se întâmplă

In [37]:
# generare numere random din intervalul [0.0, 1.0) pentru un tablou cu forma de 3,4
print ("distributie uniforma:",'\n', npr.rand(3, 4), '\n') # shape=(3,4)
 
# valori random generate dintr-o distributie normala (gaussiană)
print ("distributie normala:",'\n', npr.randn(2, 5), '\n') # shape=(2,5)

# generare de numere întregi între 1 și 50
print ("nr intregi:",'\n', npr.randint(1, 50, size=(3, 6)), '\n') # shape=(3,6)

distributie uniforma: 
 [[0.81538545 0.78836696 0.88245015 0.70960454]
 [0.03778559 0.86868418 0.73283065 0.91626668]
 [0.96270874 0.92555597 0.38516723 0.20918031]] 

distributie normala: 
 [[ 0.32504419 -0.81259639  0.39111484  0.30378502  0.36976579]
 [-0.31786538  1.95017416  0.7369119  -1.80095534  0.64434195]] 

nr intregi: 
 [[ 1 45 30 42 33 12]
 [39  2 34 24 20 39]
 [35 25 30 30 24 14]] 



In [ ]:
# shuffle
x = np.arange(10)
npr.shuffle(x)
print ("reshuffling:",'\n', x,'\n')
# npr.permutation se poate folosi pentru același scop, dar scrii mai mult

x = np.arange(10,20)
print ("alegere fără înlocuire",'\n',npr.choice(x, 10, replace=False),'\n')
print ("alegere cu înlocuire",'\n',npr.choice(x, (5, 10), replace=True),'\n') # default

### Exercițiu
- scrie o funcție care să genereze random N numere pare în intervalul 1 - 100
- folosește funcția pentru a genera N=1000 numere pare
- cu numere generate, creează o un tablou NumPy tridimensional de forma (10,10,10)
- înlocuiește cu -1 toate numerele pare divizible cu 5 și afișează rezultatul obținut

In [ ]:
# Soluția ta






### Exercițiu
Să presupunem că numărul de vânzări zilnice sunt stocate într-un array NumPy unidimensional în ordine cronologică.
- generează un tablou 1D cu 28 de numere întregi aleatoare între 1 și 100
- transformă accest tablou 1D într-unul 2D simulând un raport de vânzări lunar (4 săptămâni), în care săptămână au fost cele mai multe vânzări?
- generează o mască pentru pentru a număra zilele în care s-au vândut mai puțin de 33 de produse
- cu câte procente ar fi crescut vânzările dacă managerul impunea un obiectiv de minim 50 de vânzări zilnice și acesta ar fi fost atins în fiecare zi?

Pentru mai multe exerciții rezolvate consultați următorul link: https://www.kaggle.com/code/themlphdstudent/learn-numpy-numpy-50-exercises-and-solution

## BONUS

Acesta este un exercițiu opțional. Rezolvarea completă a acestui exercițiu vă poate aduce punctaj suplimentar la nota de la laborator (+10p).

## SQuAD dataset 
Stanford Question Answering Dataset (SQuAD) este un set de date pentru înțelegerea textelor, format din întrebări formulate de diferite persoane cu privire la un set de articole Wikipedia. Răspunsul la fiecare întrebare este un segment scurt de text, preluat dintr-un paragraf. Unele întrebări ar putea să nu aibă un răspuns clar. Pentru fiecare paragraf sunt formulate mai multe întrebări.

Mai multe detalii găsiți aici: https://rajpurkar.github.io/SQuAD-explorer/

Pentru a începe, descarcă în aceeași locație fișierul dev-v2.0 de pe moodle.

#### Citirea fișierului JSON 

In [ ]:
import json
f = open('dev-v2.0.json')  # deschidem fișierul de pe moodle
data = json.load(f)['data']  # datele vor fi încărcate sub formă de dicționar în Python - de fapt va fi o listă de dicționare

In [ ]:
# fiecare dicționar are un subiect specific (title) - primul este despre normanzi și conține doar întrebări legate de acest subiect
# titlul primului dicționar
data[0]['title']

### Task 1: Explorează setul de date
- Aruncă o privire asupra setului de date și explică modul în care este organizat.
- Extrage primul set de întrebări corespunzător primului paragraf.
- Extrage prima întrebare și răspunsurile la aceasta.

#### Descriere set de date:

Completează aici ...

In [ ]:
# Solutia ta





### Task 2: Pre-procesarea datelor
Probabil ai observat că multe răspunsuri se repetă.
- Șterge toate răspunsurile duplicat (dacă sunt două sau mai multe la fel, păstreaza unul singur)

In [ ]:
# Soluția ta






### Task 3: Statistici
- Câte subiecte (dicționare cu paragrafe) există în dataset?
- Pentru fiecare subiect, extrage numărul de paragrafe.
- Creează un tablou NumPy unidimensional cu dimensiunea (shape-ul) egală cu numărul total de paragrafe.
- Parcurge toate paragrafele și inserează în array-ul creat numărul total de întrebări pentru fiecare paragraf. 
- Folosește metode NumPy pentru a calcula numărul mediu de întrebări per paragraf.
- Calculează media numărului de cuvinte per paragraf.
- Calculează procentul de întrebări fără răspuns.

In [ ]:
# Soluția ta



